//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresZayavkaProsm
    {
        public int ID_adres { get; set; }
        public string Parametr { get; set; }
        public string Istoriya_znach { get; set; }
        public string Aktual_znach { get; set; }
        public Nullable<System.DateTime> Data_izmen { get; set; }
        public string Type_izmen { get; set; }
        public Nullable<int> ID_GAR { get; set; }
        public string Kadastr_nom { get; set; }
        public string Mun_otdel { get; set; }
        public string Administr_otdel { get; set; }
    }
}
