//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres_objects
    {
        public int ID_GAR { get; set; }
        public string Naimenovanie { get; set; }
        public int Nalog_ID { get; set; }
        public int ID_KLADR { get; set; }
    
        public virtual GAR GAR { get; set; }
    }
}
