//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullGAR
    {
        public int ID_GAR { get; set; }
        public string Mun_otdel { get; set; }
        public string Administr_otdel { get; set; }
        public int IFNSL_FL { get; set; }
        public int IFNSL_YL { get; set; }
        public int OKATO { get; set; }
        public int OKTMO { get; set; }
        public int Pochta_Index { get; set; }
        public int ID_Reestr { get; set; }
        public string Kadastr_nom { get; set; }
        public string Status_zap { get; set; }
        public System.DateTime Data_Vnesenia { get; set; }
        public System.DateTime Data_aktual { get; set; }
        public string FullAddress { get; set; }
        public Nullable<int> Nalog_ID { get; set; }
        public Nullable<int> ID_KLADR { get; set; }
        public string Period_deistviya { get; set; }
        public string Stroka_adres { get; set; }
        public Nullable<int> ID_Dok { get; set; }
        public string Type_Dok { get; set; }
        public Nullable<System.DateTime> Date_Dok { get; set; }
        public string DocumentName { get; set; }
    }
}
