//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_adres
    {
        public int ID_change { get; set; }
        public Nullable<int> ID_GAR { get; set; }
        public string Period_deistviya { get; set; }
        public string Stroka_adres { get; set; }
    
        public virtual GAR GAR { get; set; }
    }
}
