//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istor_izmen
    {
        public int ID_Izm { get; set; }
        public Nullable<int> ID_GAR { get; set; }
        public Nullable<System.DateTime> Data_izmen { get; set; }
        public string Type_izmen { get; set; }
        public Nullable<int> ID_adres { get; set; }
    
        public virtual Adres_zayavka Adres_zayavka { get; set; }
        public virtual GAR GAR { get; set; }
    }
}
