//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class UvedProsm
    {
        public int ID_Uved { get; set; }
        public Nullable<int> ID_Zayavki { get; set; }
        public string Type_zayavki { get; set; }
        public string Uroven { get; set; }
        public string Type_uved { get; set; }
        public string Status_uved { get; set; }
        public Nullable<System.DateTime> Data_ispoln_1 { get; set; }
        public Nullable<System.DateTime> Data_ispoln_2 { get; set; }
        public Nullable<System.DateTime> Data_podpis_1 { get; set; }
        public Nullable<System.DateTime> Data_pospis_2 { get; set; }
        public Nullable<System.DateTime> Data_ozhid_ispoln { get; set; }
        public string Kommentarii { get; set; }
        public string Prichina_otkaza { get; set; }
        public string CreatorName { get; set; }
        public string CreatorEmail { get; set; }
        public string Kadastr_nom { get; set; }
        public string Mun_otdel { get; set; }
    }
}
