//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uvedomleniya
    {
        public int ID_Uved { get; set; }
        public Nullable<int> ID_Zayavki { get; set; }
        public string Type_uved { get; set; }
        public string Status_uved { get; set; }
        public Nullable<System.DateTime> Data_ispoln_1 { get; set; }
        public Nullable<System.DateTime> Data_ispoln_2 { get; set; }
        public Nullable<System.DateTime> Data_podpis_1 { get; set; }
        public Nullable<System.DateTime> Data_pospis_2 { get; set; }
        public Nullable<System.DateTime> Data_ozhid_ispoln { get; set; }
        public string Kommentarii { get; set; }
        public string Prichina_otkaza { get; set; }
    
        public virtual Type_status Type_status { get; set; }
        public virtual Type_uved Type_uved1 { get; set; }
        public virtual Zayavka Zayavka { get; set; }
    }
}
