//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zayavka()
        {
            this.Uvedomleniya = new HashSet<Uvedomleniya>();
        }
    
        public int ID_zayavki { get; set; }
        public string Type_zayavki { get; set; }
        public string Uroven { get; set; }
        public Nullable<int> ID_GAR { get; set; }
        public Nullable<int> Sozdatel_zayav { get; set; }
        public System.DateTime Data_sozdaniya { get; set; }
        public System.DateTime Data_sozd2 { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual GAR GAR { get; set; }
        public virtual Type_zayavki Type_zayavki1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uvedomleniya> Uvedomleniya { get; set; }
    }
}
