//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIAS_Murt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZayavkaDetails
    {
        public int ID_zayavki { get; set; }
        public string Type_zayavki { get; set; }
        public string Uroven { get; set; }
        public System.DateTime Data_sozdaniya { get; set; }
        public System.DateTime Data_sozd2 { get; set; }
        public string Kadastr_nom { get; set; }
        public string Mun_otdel { get; set; }
        public string Administr_otdel { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> ChangeCount { get; set; }
        public string LatestDocumentType { get; set; }
        public string LatestDocumentName { get; set; }
    }
}
